version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    ports:
      - 5672:5672
      - 8001:15672

  admin:
    depends_on:
      - db
      - rabbitmq
    image: andytakker/vk-parser:latest
    restart: unless-stopped
    entrypoint: python -m vk_parser.admin
    ports:
      - 8000:80
    environment:
      APP_API_ADDRESS: 0.0.0.0
      APP_API_PORT: 80

      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      APP_AMQP_DSN: $AMQP_DSN
      APP_AMQP_PREFETCH_COUNT: $AMQP_PREFETCH_COUNT
      APP_AMQP_RETRY_PAUSE_SECONDS: $AMQP_RETRY_PAUSE_SECONDS
      APP_AMQP_RETRY_COUNT_LIMIT: $AMQP_RETRY_COUNT_LIMIT

  simple_vk_parser:
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    image: andytakker/vk-parser:latest
    entrypoint: python -m vk_parser.workers.vk --amqp-queue-name=VK_SIMPLE_DOWNLOAD
    environment:
      APP_VK_API_SECURE_KEY: $VK_API_SECURE_KEY
      APP_VK_API_SERVICE_TOKEN: $VK_API_SERVICE_TOKEN

      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      APP_AMQP_DSN: $AMQP_DSN
      APP_AMQP_PREFETCH_COUNT: $AMQP_PREFETCH_COUNT
      APP_AMQP_RETRY_PAUSE_SECONDS: $AMQP_RETRY_PAUSE_SECONDS
      APP_AMQP_RETRY_COUNT_LIMIT: $AMQP_RETRY_COUNT_LIMIT

  post_vk_parser:
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    image: andytakker/vk-parser:latest
    entrypoint: python -m vk_parser.workers.vk --amqp-queue-name=VK_DOWNLOAD_AND_PARSED_POSTS
    environment:
      APP_VK_API_SECURE_KEY: $VK_API_SECURE_KEY
      APP_VK_API_SERVICE_TOKEN: $VK_API_SERVICE_TOKEN

      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      APP_AMQP_DSN: $AMQP_DSN
      APP_AMQP_PREFETCH_COUNT: $AMQP_PREFETCH_COUNT
      APP_AMQP_RETRY_PAUSE_SECONDS: $AMQP_RETRY_PAUSE_SECONDS
      APP_AMQP_RETRY_COUNT_LIMIT: $AMQP_RETRY_COUNT_LIMIT
