"""empty message

Revision ID: 2cde9f1042fb
Revises: c0a72d105f89
Create Date: 2024-03-07 16:44:50.540183

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cde9f1042fb"
down_revision: str | None = "c0a72d105f89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__messages")),
    )
    op.create_table(
        "send_accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("login", sa.String(length=1024), nullable=False),
        sa.Column("password", sa.String(length=1024), nullable=False),
        sa.Column("secret_token", sa.String(length=1024), nullable=False),
        sa.Column("user_link", sa.String(length=1024), nullable=True),
        sa.Column("successful_messages", sa.BigInteger(), nullable=True),
        sa.Column("error_status", sa.String(length=1024), nullable=True),
        sa.Column("expire_timestamp", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__send_accounts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("send_accounts")
    op.drop_table("messages")
    # ### end Alembic commands ###
