"""add sex+city users

Revision ID: fccd8f48ec0c
Revises: c0a72d105f89
Create Date: 2024-03-10 18:22:57.895564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fccd8f48ec0c'
down_revision: Union[str, None] = 'c0a72d105f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__messages'))
    )
    op.create_table('send_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=1024), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('secret_token', sa.String(length=1024), nullable=False),
    sa.Column('user_link', sa.String(length=1024), nullable=True),
    sa.Column('successful_messages', sa.BigInteger(), nullable=True),
    sa.Column('error_status', sa.String(length=1024), nullable=True),
    sa.Column('expire_timestamp', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__send_accounts'))
    )
    op.create_table('send_messages_detail',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status_message', postgresql.ENUM('SENDING', 'QUEUED', 'FAILED', 'SUCCESSFUL', name='status_messages'), server_default='SENDING', nullable=False),
    sa.Column('success_message', sa.BigInteger(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__send_messages_detail'))
    )
    op.add_column('vk_group_user', sa.Column('sex', sa.String(length=1024), nullable=True))
    op.add_column('vk_group_user', sa.Column('city', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix__vk_group_user__city'), 'vk_group_user', ['city'], unique=False)
    op.create_index(op.f('ix__vk_group_user__sex'), 'vk_group_user', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__vk_group_user__sex'), table_name='vk_group_user')
    op.drop_index(op.f('ix__vk_group_user__city'), table_name='vk_group_user')
    op.drop_column('vk_group_user', 'city')
    op.drop_column('vk_group_user', 'sex')
    op.drop_table('send_messages_detail')
    op.drop_table('send_accounts')
    op.drop_table('messages')
    # ### end Alembic commands ###
